### ISSUE TITLE
Consider merging metabolic disease nodes: EFO_0000589 and MONDO:0024297

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#461] opened 2019-06-06 11:07 UTC
They both have the same parent and similar set of children:
`MONDO:0024297` nutritional or metabolic disease
`EFO_0000589` metabolic disease

**Comment by paolaroncaglia** [comment] 2019-06-14 15:28
Hi @d0choa ,
MONDO:0024297 'nutritional or metabolic disease' and EFO_0000589 'metabolic disease' are not equivalent and should not be merged. However, MONDO:0024297 'nutritional or metabolic disease' has two children, 'nutritional disorder' and 'metabolic disease', all this is clearer if you look it up in MONDO rather than OLS: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024297 
and yes MONDO:0005066 'metabolic disease' is equivalent to EFO_0000589 'metabolic disease'.
That is also why MONDO:0005066 'metabolic disease' wasn't imported.
I believe we could consider merging EFO_0000589 'metabolic disease' into MONDO:0005066 'metabolic disease'. I'll discuss with the EFO group and get back to you.
Thanks,
Paola

**Comment by zoependlington** [comment] 2019-06-20 13:55
@paolaroncaglia, just a quick look (you may be already aware of this! If so, please ignore me). We already import MONDO:0005066 'metabolic disease' and merge with EEFO_0000589 'metabolic disease', see this line from the mapping file:
`http://purl.obolibrary.org/obo/MONDO_0005066	http://www.ebi.ac.uk/efo/EFO_0000589	metabolic disease	metabolic disease`

**Comment by paolaroncaglia** [comment] 2019-06-21 15:16
@d0choa @zoependlington 
Summing up, the correct thing to do would be to place EFO 'metabolic disease' as a child of (subclass of) MONDO 'nutritional or metabolic disease'. Would this create problems for OT therapeutic areas? If easier, we can address after our meeting.Thanks.

**Comment by d0choa** [comment] 2019-06-21 15:34
This will work for us. The main issue for us was having them side-by-side. As long as one is the child of the other we could define either of them as our therapeutic area. Thanks

**Comment by paolaroncaglia** [comment] 2019-07-02 13:10
Closing as duplicate of #494

**Closed** 2019-07-11 10:07 UTC
Labels: duplicate
