### ISSUE TITLE
Review mastitis

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#506] opened 2019-07-10 09:11 UTC
Comment from S.:

Review EFO:1001034 mastitis (currently subclass of reproductive system disease and breast disease). The current definition points to lactation mastitis or puerperal mastitis (then it should sit under the new TA “Pregnancy, puerperium and perinatal conditions“ or one of its children), but mastitis can occur in non-breastfeeding women too, and rarely in men, see https://www.nhs.uk/conditions/mastitis/ and https://en.wikipedia.org/wiki/Mastitis#Types.  – Could this go to 1) Reproductive or Breast Disorder TA as well as 2) Infection TA?

**Comment by zoependlington** [comment] 2019-10-04 15:05
https://github.com/EBISPOT/efo/issues/492

**Comment by paolaroncaglia** [comment] 2019-11-22 15:03
Closing as duplicate of (part of) https://github.com/EBISPOT/efo/issues/492.

**Closed** 2019-11-28 11:08 UTC
Labels: Open Targets, duplicate
