### ISSUE TITLE
New Robot form terms request for Buckner PMID 37057071

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2059] opened 2023-07-28 14:33 UTC
Robot request form for oxylipin measurement terms:
https://docs.google.com/spreadsheets/d/1RGHetpXZ9YG7KFwH_eZ6ICL0fuJuFSw7RxH-m7awQTk/edit?usp=sharing

Manually mapped to CHEBI or HMDB if there is no CHEBI term. 

I've put plasma in the label names... Let me know if that's wrong or there's anything else I should amend.

**Comment by ar-ibrahim** [comment] 2023-08-22 10:59
There’s a bit of an issue with some of the requested [terms](https://docs.google.com/spreadsheets/d/1RGHetpXZ9YG7KFwH_eZ6ICL0fuJuFSw7RxH-m7awQTk/edit#gid=63022977).They’re ‘lipid/metabolite in plasma’ terms so can be added to OBA using the [EQL](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/entity_attribute_location.tsv) (entity-quality-location) pattern, with the entity being a CHEBI/LipidMaps term. The authors provide abbreviations in [Supp T1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10086335/#SM1) and they all exist in CHEBI. The problem is that some of these CHEBI terms don’t actually have the requested terms as synonyms. For example:


GWAS request | synonym (in supp file) | CHEBI | CHEBI synonyms
-- | -- | -- | --
plasma oxylipin 9-hydroxylinoleic acid measurement | 9-HODE | [CHEBI:72651](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_72651) | (10E,12Z)-9-HODE; (10E,12Z)-9-hydroxyoctadeca-10,12-dienoic acid; 9-hydroxy-10E,12Z-octadecadienoic acid; 9-hydroxy-trans-10,cis-12-octadecadienoic acid

We can create the OBA term using 9-HODE [CHEBI:72651](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_72651), so the term will be **“level of  9-HODE in blood plasma”** with **"9-hydroxylinoleic acid level"** as an `exact synonym` and the PMID as an `x-ref`.  There are other examples in the [Notes](https://docs.google.com/spreadsheets/d/1RGHetpXZ9YG7KFwH_eZ6ICL0fuJuFSw7RxH-m7awQTk/edit#gid=63022977) tab.

Let me know if you have any other suggestions :) @zoependlington @earlEBI

**Comment by rays22** [comment] 2023-08-31 10:30
> We can create the OBA term using 9-HODE [CHEBI:72651](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_72651), so the term will be **“level of 9-HODE in blood plasma”** with **"9-hydroxylinoleic acid level"** as an `exact synonym` and the PMID as an `x-ref`. There are other examples in the [Notes](https://docs.google.com/spreadsheets/d/1RGHetpXZ9YG7KFwH_eZ6ICL0fuJuFSw7RxH-m7awQTk/edit#gid=63022977) tab.

@ar-ibrahim , @earlEBI 
1. I have checked in the paper and the supplement, but `oxylipin 9-hydroxylinoleic acid` is not used anywhere by the authors. No need capture that synonym in OBA. I think @earlEBI 's intention is to imply in the term label that this lipid as an `oxylipin`.
If `CHEBI:72651 9-HODE` or `9-Hydroxylinoleic acid` is indeed an oxylipin-type lipid, then it should be apparent from the CHEBI or LipidMaps class hierarchy and definitions (which are automatically incorporated into OBA).
If it were important to categorise `CHEBI:72651 9-HODE` as a subclass of `CHEBI:61121 oxylipin`, then the issue should be raised with ChEBI or LipidMaps, and the experts will decide if that is the correct chemical category.
Categorising chemicals and creating a shadow hierarchy is not in scope for OBA I am afraid.
2. @ar-ibrahim , You can use the label `level of 9-hydroxylinoleic acid in blood plasma` to reflect the full name of the chemical used in the paper supplement and optionally add the ChEBI-based chemical name as an exact synonym. The ChEBI component in the OBA definition unambiguously, but implicitly associates the OBA term with the ChEBI label and all the ChEBI synonyms.

**Comment by earlEBI** [comment] 2023-09-13 14:55
@rays22 I think I was just trying to provide detail and consistency. All the traits are described as oxylipins in Supplementary Table 1 by the authors, but I'm happy if you agree the the 'full name' columns describes sufficiently, along with the mapping codes. Thanks!

**Comment by ar-ibrahim** [comment] 2023-10-03 14:46
Hey @earlEBI Lizzy :) The [terms](https://docs.google.com/spreadsheets/d/1RGHetpXZ9YG7KFwH_eZ6ICL0fuJuFSw7RxH-m7awQTk/edit#gid=1084324453) have been created in OBA, imported into EFO and will be made available following the upcoming OBA and EFO (3.59.0) releases.

**Comment by earlEBI** [comment] 2023-10-03 15:35
@ar-ibrahim thank you!

**Closed** 2023-11-15 15:32 UTC
Labels: GWAS Catalog, OBA
