### ISSUE TITLE
Exome sequencing is wrongly in under transcription profiling

### ISSUE THREAD

**Issue by kpalin** [EBISPOT/efo#969] opened 2021-02-11 15:01 UTC
Term Exome sequencing http://www.ebi.ac.uk/efo/EFO_0005396 is placed under "RNA assay" and "transcription profiling" even though it is a "DNA assay" and should be sibling of "whole genome shotgun sequencing" http://www.ebi.ac.uk/efo/EFO_0003744

## Attribution

https://orcid.org/0000-0002-4621-6128

**Comment by paolaroncaglia** [comment] 2021-02-11 15:53
Hi @kpalin ,

Thank you for pointing this out. The issue is related to https://github.com/ebispot/efo/issues/887, so I'll bring your comment over there and will close this ticket as duplicate. You may subscribe to https://github.com/ebispot/efo/issues/887 if you'd like to receive updates. 

Thanks, and best wishes,

Paola Roncaglia

**Closed** 2021-02-11 15:55 UTC
