### ISSUE TITLE
"urinary system disease" (EFO:0009690) as part of "disease of genitourinary system" (EFO:0009663)

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#464] opened 2019-06-12 17:04 UTC
Currently "urinary system disease" (EFO:0009690) and "disease of genitourinary system" (EFO:0009663) are both children of disease by anatomical system while the first should be contained in the second.

**Comment by paolaroncaglia** [comment] 2019-07-02 13:16
Closing as duplicate of #492

**Closed** 2019-07-11 10:07 UTC
Labels: duplicate
