### ISSUE TITLE
Open Targets therapeutic area: blood and lymphatic system disorders 

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#485] opened 2019-07-02 12:28 UTC
cc @zoependlington 
As agreed at a meeting today with @d0choa, Sandra Machlitt-Northen and @simonjupp, this ticket is the first one in a series of 15, all of them about the new MedDRA-like therapeutic areas that Open Targets would like to have. To start with, in each ticket I will simply copy the request from Open Targets as is. As we work on each ticket, if we realize that we need to deviate from OT's suggestion, we will add comments and discuss with them.

Proposed TA name: Blood and lymphatic system disorders 
Current EFO TA name: Hematologic disease
Priority for OT: Low
Justification: The lymphatic system supports the circulatory system by draining excess fluids and proteins from tissues back into the bloodstream. They both support the immune system.   https://www.ncbi.nlm.nih.gov/books/NBK22211/

Hematology = the branch of medical science dealing with the blood and blood-forming tissues, including morphology, physiology, and pathology. adj., adj hematolog´ic.  https://medical-dictionary.thefreedictionary.com/Hematology
Lymphatic: 1. pertaining to lymph or to a lymphatic vessel., 2. a lymphatic vessel. lymphatic ducts the two large vessels into which all lymphatic vessels converge. The right lymphatic duct joins the venous system at the junction of the right internal jugular and subclavian veins and carries lymph from the upper right side of the body. The left lymphatic duct, or thoracic duct, enters the circulatory system at the junction of the left internal jugular and subclavian veins; it returns lymph from the upper left side of the body and from below the diaphragm. Lymphatic system: the lymphatic VESSELS and lymphoid TISSUES considered collectively. https://medical-dictionary.thefreedictionary.com/Lymphatic+system
blood = the fluid that circulates through the heart, arteries, capillaries, and veins and is the chief means of transport within the body. It transports oxygen from the lungs to the body tissues, and carbon dioxide from the tissues to the lungs. It transports nutritive substances and metabolites to the tissues and removes waste products to the kidneys and other organs of excretion. It has an essential role in the maintenance of fluid balance. https://medical-dictionary.thefreedictionary.com/blood

ACTION: 
Rename “hematological disease” to “Blood and lymphatic system disease” This will be a TA name. 
Split Blood and Lymphatic diseases into 2 ‘groups’ sitting under the TA. Currently,  Lymphatic system disease sits under hematologic disease [and lymphoid system disease]

**Comment by paolaroncaglia** [comment] 2019-07-10 11:06
A quick note that in EFO 'lymphatic vessel' is part of 'cardiovascular system'. If OT wishes for "Lymphatic diseases" to be about lymphatic vessels as well as lymph, we'll need to work on that link or it will cause unwanted inferences - or on how we define "Lymphatic diseases".

**Comment by d0choa** [comment] 2019-07-11 10:03
There is a problem here. Uberon definitions says:
- [Cardiovascular system](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0004535): Anatomical system that has as its parts the **heart** and **blood vessels**

This agrees with other ontologies such as Mesh:
- [cardiovascular system](https://www.ncbi.nlm.nih.gov/mesh/68002319): The **HEART** and the **BLOOD VESSELS** by which BLOOD is pumped and circulated through the body

The problem is that one of the children of "cardiovascular system" is:
- [vascular system](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0007798): Anatomical system that consists of all **blood** and **lymph vessels**.

Ontologically this looks incorrect, as the lymph vessels will not be part of the cardiovascular system based on the above definition. Some other definitions also focus on the vascular system being exclusively about blood:
- [medical-freedictionary](https://medical-dictionary.thefreedictionary.com/vascular): pertaining to **blood vessels** or indicative of a copious blood supply.
Whereas you might find alternative definitions where they include the lymph (e.g. FMA).

Both Meddra and Mesh exclude lymph vessels from the cardiovascular system and keep them under the immune system.. This will be the ideal result for OT.

**Comment by zoependlington** [comment] 2019-08-08 10:55
A start to organise the current subclasses of hematologic disease: https://docs.google.com/spreadsheets/d/1z2TzqEdoYPSWK11jS8BilmbA5Ft8lZbNsd-3xJau_OQ/edit?usp=sharing

@d0choa @smnorthen please feel free to edit or comment as you see fit, I have only assigned a disease location on the spreadsheet where the definition in EFO points towards either blood or lymphatic system.

**Comment by smnorthen** [comment] 2019-08-09 09:31
@zoependlington - I have added my comments to the document. Happy to discuss further if needed.

**Comment by zoependlington** [comment] 2019-08-09 09:54
@smnorthen Thank you! I will be slowly doing the same with the other TAs so this is a huge help!

**Comment by paolaroncaglia** [comment] 2019-10-04 15:44
@zoependlington 
EFO:0005803 hematologic disease has an rdfs: comment "placeholder for lymphoid disease". (Mondo inherits it from us, too.) We now have  EFO > MONDO:0044986 lymphoid system disease, so perhaps we could delete that comment? Happy to do it myself, but double-cheking just in case. Thanks.

**Comment by zoependlington** [comment] 2019-10-07 15:11
@paolaroncaglia EFO:0005803 hematologic disease in the slim is renamed blood or lymphatic system disease, perhaps we can rename the term as well as removing the comment?

**Comment by paolaroncaglia** [comment] 2019-10-08 10:06
@zoependlington and I discussed her question above and agreed that further discussion will be needed to see if/how we can better align slim/profile and EFO3. (In brief, hematologic disease is broader than blood disease, so we'd need to look at all its children to see if we can rehouse them - and if that's appropriate or not.) To be updated at a later time.

**Comment by zoependlington** [comment] 2019-10-18 10:55
TA has been renamed hematologic or lymphatic system disease.

**Comment by zoependlington** [comment] 2019-11-19 15:36
Closing this ticket as all relevant work is now in https://github.com/EBISPOT/efo/issues/595

**Closed** 2019-11-28 11:08 UTC
Labels: Open Targets
