### ISSUE TITLE
Open Targets therapeutic areas: cardiac disorders + vascular disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#486] opened 2019-07-02 12:31 UTC
Proposed TA name:     
1. Cardiac disorders 
2. Vascular disorders
Current EFO TA name: Cardiovascular disease
Priority for OT: High
Justification: See definitions below, cardiac should include the heart and associated blood vessels, Vascular refers to any blood vessel

car·di·ac = 1. Pertaining to the heart., 2. Pertaining to the esophageal opening of the stomach. , 3. (Obsolete). A remedy for heart disease. https://medical-dictionary.thefreedictionary.com/cardiac
Cardiovascular = pertaining to the heart and blood vessels. https://medical-dictionary.thefreedictionary.com/cardiovascular
vascular = pertaining to blood vessels or indicative of a copious blood supply. https://medical-dictionary.thefreedictionary.com/vascular

Currently in EFO:
[OLS view of 'heart disease' and 'vascular disease']

ACTION:
Update the therapeutic area list (ontology will keep the same):
remove cardiovascular disease
add heart disease
add vascular disease
We can do a pull-request for this action

**Comment by paolaroncaglia** [comment] 2019-07-03 14:06
Note for self: I'll document my brain dump here.

**Comment by paolaroncaglia** [comment] 2019-07-05 14:23
Summary for requested OT TAs cardiac disorders + vascular disorders:

cardiac disorder already exist in EFO as EFO:0003777 heart disease
Subclass of cardiovascular disease and thoracic disease

vascular disorder already exist in EFO as EFO:0004264 vascular disease
Subclass of cardiovascular disease

In order for heart disease + vascular disease to be directly under disease, we’d need to 

- Delete cardiovascular disease
- Delete thoracic disease

But:

- cardiovascular disease is used by the GWAS Catalog, and deleting it would break GWAS’ pipeline. If we don’t delete it from EFO, we could give OT a slim that doesn’t contain it, but we’d still have to rehouse all of its children for the OT TAs to work; and GWAS would have no use for an “empty” cardiovascular disease.
- cardiovascular disease has mappings (database cross-references) to MeSH, ICD (9 and 10), NCIt, SNOMED, DOID, UMLS, plus MONDO. If we delete it, those useful mappings are lost; if we make it childless, those mappings become meaningless.
- cardiovascular disease has 33 children in addition to heart disease + vascular disease. They need looking at to assess where they could be rehoused. At a very quick glance, several children seem to map to blood and lymph, so the general question is - keep blood and lymph disorders completely disjoint from vascular system? How does MONDO address that? This is an important point to address regardless of the final decision wrt TAs, but will take some time.
- cardiovascular disease is used in axioms of 28 measurement terms. We’d need to look at and change each one of them. This is a potentially useful exercise regardless of the final decision wrt TAs, but will take some time.
- One of the other requested TAs is “Respiratory, thoracic and mediastinal disorders”, so cardiac disorder, as a type of thoracic disease, would have to sit under the TA “Respiratory, thoracic and mediastinal disorders”, unless we delete ‘disorder by anatomical region’.
- Deleting ‘disorder by anatomical region’ and ‘thoracic disease’ would impact EFO’s alignment with MONDO.
- As far as I can tell, cardiovascular is a relevant grouping for the medical field, and since the two TAs you’re looking for (heart disease + vascular disease) already exist in EFO under cardiovascular disease, from a biomedical standpoint I’m not sure why you’d want to remove a commonly used grouping term such as cardiovascular.

**Comment by zoependlington** [comment] 2019-07-09 12:47
Check children of cardiovascular disease to see if they can be classified under heart disease, vascular disease or the other therapeutic area for blood disease.

**Comment by paolaroncaglia** [comment] 2019-07-10 10:27
As agreed above, here's a review of all children of 'cardiovascular disease', shortened in CVD, starting from the top in the OLS view:

- [ ]  EFO > Orphanet:168612 Congenital deficiency in alpha-fetoprotein "Congenital deficiency in alpha-fetoprotein is a benign genetic condition characterized by a dramatically decreased level of alpha-fetoprotein in fetus or neonate. [ Orphanet:168612 ] "
=> delete link to CVD 

To be continued

**Comment by paolaroncaglia** [comment] 2019-07-10 13:38
Continued:

- [ ] EFO:1000782 altitude sickness
We debated its location in https://github.com/EBISPOT/efo/issues/383. In the end we didn't make it a direct child of 'disease' because we couldn't really reach a decision. But perhaps we should. If so, re-open #383.

**Comment by d0choa** [comment] 2019-07-16 19:43
Notes from S. on some of these actions:

- All the leukemia/lymphoma terms  – Could go to Neoplasm TA and TA Blood & lymphatic tissue disorder
- EFO:1000782 Altitude sickness (also linked to ticket: #383.) - Could go to a Respiratory TA. Definition is [here]( https://medical-dictionary.thefreedictionary.com/altitude+sickness): “Altitude sickness occurs because the partial pressure of oxygen decreases with altitude. (…) there is a substantially lower amount of oxygen available for the individual to inhale “ It shouldn’t go to some blood related TA as it’s the oxygen intake that’s the problem, thus resulting in too little oxygen in the blood. But it is not a blood disorder.
- Congenital anomaly of cardiovascular system – Maybe consider moving this to the Congenital/Genetic TA. Note from @d0choa: under both (congential + CVD) would make sense for us

**Comment by paolaroncaglia** [comment] 2019-07-30 15:17
Continued from above (OLS view under CVD, from epistaxis down):

- [ ] EFO:0003895 epistaxis
Change parent CVD into more specific vascular disease, and add parent hemorrhage.

TBC

**Comment by paolaroncaglia** [comment] 2019-07-30 16:21
@d0choa 
Could you and Sandra please provide feedback on the placement of EFO > MONDO:0000474 'pericardium disease' with regards to the therapeutic areas of cardiac disorders and/or vascular disorders. It is currently a direct child of cardiovascular disease (CVD) (as well as thoracic disease).  Its textual and logical definitions point to pericardium which _contains_ the heart and the roots of the great vessels; for the OLS view of pericardium, see https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002407 
We would keep this term under CVD in EFO, but for the OT TAs, would it be enough to have it under the thoracic disease TA? Perhaps we could also place it under connective tissue disease based on the composition of the pericardium, but I'm really not sure because of its multi-tissue structure.

Thanks,

Paola

**Comment by d0choa** [comment] 2019-07-31 09:07
Reply from Sandra:
Pericardium disease would best go to Cardiac disease (cardiac disorders are defining the heart and associated blood vessels, whereby vascular disorders are pertaining to the blood vessels not associated with the heart). It should not go to connective tissue disease.

**Comment by d0choa** [comment] 2019-07-31 09:14
Regarding the thoracic disease, we are aiming to make this TA obsolete as it refers to a purely anatomical region with no clinical relevance. Meddra has no equivalent `System organ class`, so we expect to accommodate all diseases currently contained there in at least 1 other TA.

**Comment by paolaroncaglia** [comment] 2019-07-31 10:37
@d0choa (and Sandra)
Thanks. Could you please let me know what exactly is your source for "cardiac disorders are defining the heart _and associated blood vessels_", so I can quote that in EFO. I can see the logic, but I'd like to avoid the reasoner throwing errors if possible. I might need to create cardiac disease as a parent of heart disease - or I might simply delete the location axiom from pericardium disease - I'd like to find an  easily maintainable solution. The only place where I could easily find "cardiac" as referring to heart as well as its surroundings is the Merriam-Webster: "of, relating to, situated near, or acting on the heart" (https://www.merriam-webster.com/dictionary/cardiac).
Thanks,
Paola

**Comment by paolaroncaglia** [comment] 2019-07-31 10:44
Continued from above (OLS view under CVD, last two children):

- [ ] EFO:0005576 pernicious anemia
Should not be child of CVD. Presumably this is due to the disease location axiom pointing to blood. If so, that should be fixed when we remove blood from being a part of cardiovascular system, see above. It's already in the hematologic disease TA.

- [ ] EFO:0007481 septicemic plague
Should not be child of CVD. Presumably this is due to the disease location axiom pointing to blood. If so, that should be fixed when we remove blood from being a part of cardiovascular system, see above. It's already in the hematologic disease TA.

- [ ] EFO:0004264 vascular disease
By definition, it comprises the lymphatic vessels, but OT would like a separate TA for lymphatic system disorders. That might still be ok, but need to check.

**Comment by paolaroncaglia** [comment] 2019-07-31 10:51
@d0choa 
please note, I extended my comment/question to you above, thanks.

**Comment by d0choa** [comment] 2019-07-31 11:39
The UBERON class `heart plus pericardium` is what we were aiming for. If you look at [Mesh](https://www.ncbi.nlm.nih.gov/mesh/68006321) the `heart` class includes the `pericardium`. However, their definition is not very verbose and makes no distinction.

We would advise against "cardiac disease as a parent of heart disease" as cardiac and heart should be synonyms.

Sandra found some accurate definitions in this [page](https://www.wakehealth.edu/Service-Line/h/Heart-and-Vascular):
- heart: Heart care involves medical care or surgical treatment for problems that affect your heart and its arteries and blood vessels.
- vascular: Vascular care involves medical management and surgical treatment of problems affecting circulation outside the heart and brain, especially the legs, arms, neck and kidneys

**Comment by d0choa** [comment] 2019-07-31 11:51
See #485 for discussion about lymphatic vessels

**Comment by paolaroncaglia** [comment] 2019-07-31 13:01
@d0choa and Sandra
Thanks for your prompt feedback, I do appreciate it.
All things considered then, I think it would be quicker and simpler to make pericardium disease a child of heart disease (exact synonym cardiac disease) in the slim for OT TAs only, and keep it as it is in 'regular' EFO. Should be an acceptable compromise for the time being. That would avoid having to make cardiac disease different from heart disease. The descriptions from the Wake Forest health provider are helpful, but I'm afraid not ideal as ontology references :-) 
Best,
Paola

**Comment by paolaroncaglia** [comment] 2019-07-31 13:30
Note for self: summing up, in short,
- [ ] fix "location" of blood and lymphatic vessels
- [ ] address all points (checkboxes) listed in this ticket
- [ ] put heart disease and cardiac disease in subset of therapeutic areas (and take away cardiovascular disease?)
- [ ] for the OT TA EFO slim, have pericardium disease a child of heart disease.

**Comment by d0choa** [comment] 2019-07-31 13:48
This solution will work for us. However, we think the proposed changes are not an OT specific problem and will benefit EFO as a whole.

Since the UBERON [pericardium](http://purl.obolibrary.org/obo/UBERON_0002407) is a child of UBERON [heart](http://purl.obolibrary.org/obo/UBERON_0000948), we understand [pericardium disease](http://purl.obolibrary.org/obo/MONDO_0000474) should be a child of [heart disease](http://www.ebi.ac.uk/efo/EFO_0003777) and not of [cardiovascular disease](http://www.ebi.ac.uk/efo/EFO_0000319).

We thought it will be simple as UBERON provides the desired anatomical description. If the problem is with the definition we can try to find a better source, but the one we trust the most we can not share ;)

**Comment by paolaroncaglia** [comment] 2019-07-31 14:41
Thanks @d0choa . That's the problem - UBERON pericardium is _not_ part of UBERON heart; it is part of UBERON 'heart plus pericardium', see the section on "Superclasses & Asserted Axioms" in the Ontobee link you provided above. UBERON heart refers to the muscle alone, and UBERON pericardium refers to the sac around the heart. To my knowledge, those UBERON anatomical descriptions are shared by the community. I understand the reasons why the OT view would like pericardium diseases associated with heart diseases, and I understand that cardiac doctors deal with pericardium as well as heart, and we'll have that in the slim we'll provide to you. But to have the same in EFO, we would need the disease class to refer to 'heart plus pericardium', and then we can't call it 'heart disease' because that refers to heart alone. And we can't call it cardiac disease either because that's an exact synonym of heart disease. It soesn't simply depend on the definition. As I said, don't worry, it will be ok in the slim we'll provide. :-)

**Comment by d0choa** [comment] 2019-07-31 14:57
Sorry it feels like I'm misreading the ontology and waisting your time.

Can I have an extra question for me to understand? Why does the [OLS pericardium entry](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002407) show `part_of some heart` as a Term relationship? This and the OLS tree made me think that according to UBERON `pericardium` is a part of the `heart`.

**Comment by paolaroncaglia** [comment] 2019-07-31 15:07
@d0choa 
No problem at all. Yes the OLS view of the EFO pericardium term is confusing and doesn't reflect the placement that the term should have based on the UBERON file that EFO imports (and that shows the same as the Ontobee view we discussed). @zoependlington and @S2Ola are looking into this issue in case something went wrong during the UBERON import. It's good that we spotted this! Thanks David!

**Comment by paolaroncaglia** [comment] 2019-07-31 16:00
@d0choa 
FYI, my colleagues have identified the issue and will address it over the next couple of days. The fix may not be immediately visible in the EFO version in OLS, so for the time being, if you wish/need to double-check the placement of anatomy terms, please refer to the UBERON version currently in OLS. To make things even more interesting, please be aware that the UBERON version loaded in Ontobee is 6 months behind (OLS has the most recent one, but the default URI for UBERON terms redirects to Ontobee!).
This said, while I wait for the issue to be fixed, I'll continue to work on the TAs.
Best,
Paola

**Comment by paolaroncaglia** [comment] 2019-10-04 13:29
Note for self:
Most issues in this ticket have been addressed via creation of an OT TA slim/profile.
Other issues in this ticket will be addressed as part of https://github.com/EBISPOT/efo/issues/571.
I'll check boxes as I go to reflect the above, so I can focus on what really still needs to be done in EFO3.

**Comment by paolaroncaglia** [comment] 2019-11-06 09:27
Note for self: left to do for this ticket: looking at the post-reasoner inferred view in Protege, 
- [ ] review the direct children of 'cardiovascular disease' and address why some are still there that shouldn't (seems to be a mix of Orphanet issues and Mondo inheritance);
- [ ] review the direct children of 'heart disease' and 'vascular disease': if any still have the (now redundant) cardiovascular disease parent coming from EFO, delete it.

**Comment by paolaroncaglia** [comment] 2019-12-10 09:34
Note for self, opened a Mondo ticket for 'fibromuscular dysplasia' (https://github.com/monarch-initiative/mondo/issues/1029).

**Comment by paolaroncaglia** [comment] 2019-12-13 10:44
@smnorthen
@d0choa 
I've finished the revision of the cardiac + vascular disease areas as outlined in this ticket. There may still be issues with Orphanet terms and their parentage, but those will be addressed elsewhere. If you spot any problem with EFO-specific (or Mondo) descendants of cardiac + vascular diseases at a lower/more granular level, please let us know by opening new tickets. Thanks.

**Closed** 2020-01-09 14:38 UTC
Labels: Open Targets
