### ISSUE TITLE
Merge/Group Genetic diseases

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#463] opened 2019-06-06 14:39 UTC
Currently, the ontology contains these 2 terms under disease:
- EFO:0000508 - genetic disorder
- MONDO:0003847 - inherited genetic disease

If different, it would be convenient to have them grouped under the same parent. The resulting term would be a useful `therapeutic area`

**Comment by d0choa** [comment] 2019-06-12 17:20
In fact, other ontologies group these two terms with a third children of disease "congenital abnormality" (MONDO:0000839) to form a bigger node. This would be handy if implemented in EFO:
- MedDRA: [Congenital, familial and genetic disorders](https://bioportal.bioontology.org/ontologies/MEDDRA/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMEDDRA%2F10005329)
- MeSH: [Congenital, Hereditary, and Neonatal Diseases and Abnormalities](https://meshb.nlm.nih.gov/record/ui?ui=D009358)

**Comment by paolaroncaglia** [comment] 2019-06-21 16:09
@d0choa (and @zoependlington )
Let’s look at inherited/genetic disease/disorder first:
MONDO:0003847 ‘inherited genetic disease’ (“A disease that is caused by genetic modifications where those modifications are inherited from a parent's genome.”) 
Is indeed the same as
EFO:0000508 ‘genetic disorder’ (“Genetic diseases are diseases in which inherited genes predispose to increased risk. ...”)
In fact, MONDO:0003847 is xref’d to EFO:0000508, but not the other way round, and so both terms coexist in EFO. Both terms cover only inherited genes and exclude somatic genetic mutations (see def of EFO term and comment on MONDO term). 
@simonjupp @zoependlington  if you agree with me that these terms mean the same, I suggest to
- [ ] Label EFO:0000508 ‘genetic disorder’ as ‘inherited genetic disorder’ to make that clear, or even better to ‘inherited genetic disease’ for consistency with MONDO, and
- [ ] Add to the mapping files accordingly.
- [ ] If we manage to clean up some of the ‘rare genetic x diseases’ (#452) beforehand, that might avoid build errors, but I’m not sure if that’d be necessary (Zoe?)
- [ ] Once we’ve addressed the above, we can discuss addition of an uberclass similar to
MedDRA: Congenital, familial and genetic disorders
MeSH: Congenital, Hereditary, and Neonatal Diseases and Abnormalities
As David suggests and if that would be helpful to Open Targets (I notice that MONDO doesn’t have it, but that doesn’t mean we couldn’t add it).

**Comment by zoependlington** [comment] 2019-06-24 07:59
@paolaroncaglia This sounds great to me, definitely add to the mapping file. It shouldn't cause too many issues, but if it does we will have to investigate the rare genetic x diseases for sure.

**Comment by simonjupp** [comment] 2019-06-27 09:24
This all sounds reasonable to me @paolaroncaglia

**Comment by paolaroncaglia** [comment] 2019-06-27 09:51
Note for self:
To answer the question "are there any genetic diseases in EFO that are not inherited and that wouldn't fit under 'inherited genetic disease/disorder' ", double-check if we have any classes of somatic mutations causing diseases (e.g. some types of cancer?) that should _unequivocally_ sit under a separate group of 'non-inherited/somatic genetic disease/disorder'; in case, we may want to consult with MONDO too.

**Comment by paolaroncaglia** [comment] 2019-07-02 13:12
Closing as duplicate of #493

**Closed** 2019-07-11 10:07 UTC
Labels: duplicate
