### ISSUE TITLE
Mediastinal disease (MONDO_0043707) currently as region and system 

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#465] opened 2019-06-13 16:51 UTC
Mediastinal disease (MONDO_0043707) is currently annotated under "disease by anatomical system" and "disease by anatomical region". This is very uncommon across EFO, so I'm wondering if this should be assigned only to either one of the terms (region or system).

**Comment by paolaroncaglia** [comment] 2019-07-02 13:17
Closing as duplicate of #499

**Closed** 2019-07-11 10:07 UTC
Labels: duplicate
