### ISSUE TITLE
Review placement of Pubic Symphysis Diastasis

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#505] opened 2019-07-10 09:09 UTC
Comment from S.:

Review placement of EFO:1001833 Pubic Symphysis Diastasis (currently subclass of reproductive system disease). The pubic symphysis is located near genitalia in males and females, but is indeed a cartilaginous joint. See https://en.wikipedia.org/wiki/Pubic_symphysis and UBERON:0003699. - Maybe this would be best linking to the Musculoskeletal & Connective tissue Disorder TA

**Comment by zoependlington** [comment] 2019-10-04 15:05
https://github.com/EBISPOT/efo/issues/492

**Comment by paolaroncaglia** [comment] 2019-11-22 14:43
Closing as duplicate of (part of) https://github.com/EBISPOT/efo/issues/492.

**Closed** 2019-11-28 11:08 UTC
Labels: Open Targets, duplicate
