### ISSUE TITLE
UniProtKB 2019_10 release OMIM to EFO mappings

### ISSUE THREAD

**Issue by ggeorghiou** [EBISPOT/efo#593] opened 2019-10-16 10:51 UTC
Hi all,

We have new a new release with OMIM terms that I have mapped to EFO. In cyan are the new term requests, red is phenotypes that I have not mapped, and ones not highlighted are OMIM IDs that can be mapped to existing EFO terms or MONDO/Orphanet terms that we'd like to see added to EFO. The link is below.

https://docs.google.com/spreadsheets/d/11ndNVMgglsEWlu6JM1HE5bA_umX-0YSPD4wa9SDPkmU/edit?usp=sharing

Thanks in advance.

**Comment by paolaroncaglia** [comment] 2019-11-18 13:46
Same - pinning this ticket as, ideally, we should address it before its submitter leaves EBI, in case we have questions. Therefore I'll aim to complete it before the end of November.

**Comment by paolaroncaglia** [comment] 2019-11-19 08:39
Moving this ticket to "Done" as this is now a duplicate of https://github.com/EBISPOT/efo/issues/588.

**Closed** 2019-11-28 11:08 UTC
Labels: Open Targets
