### ISSUE TITLE
Autoimmune Bullous Disease cleanup

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#75] opened 2018-02-12 11:03 UTC
Subepidermal autoimmune bullous diseases of the skin and mucosae comprise a large group of chronic diseases, including bullous pemphigoid, pemphigoid gestationis, mucous membrane pemphigoid, linear IgA bullous dermatosis, epidermolysis bullosa acquisita, and anti-p200 pemphigoid. These diseases are characterized by an antibody response toward structural components of the basement membrane zone, resulting in subepidermal blistering. 

Some of the diseases are already in EFO but are lacking synonyms, x-refs and classification can be enhanced to have them well represented and linked to the causal genes.

## Preferred term label

- vesiculobullous skin disease  (http://www.ebi.ac.uk/efo/EFO_1000774). Merge with bullous skin disease. 'vesiculobullous skin disease' becomes a synonym of 'bullous skin disease'
- autoimmune bullous skin disease (missing: )
- pemphigus (http://www.ebi.ac.uk/efo/EFO_1000749, UMLS C0030807, NCIT_C34909, MeSH D010392)
- pemphigus vulgaris (http://www.ebi.ac.uk/efo/EFO_0004719)
- pemphigus foliaceus (missing: Orphanet_79481, UMLS C0263313, see MONDO_0019324)
- pemphigus erythematosus (missing: Orphanet_79480, see MONDO_0019323)
- paraneoplastic pemphigus (missing: Orphanet_63455, see MONDO_0018974)
- Anti-p200 pemphigoid (missing: Orphanet_454710, MONDO_0018688)
- pemphigus herpetiformis (missing https://emedicine.medscape.com/article/1064550-overview)
- pemphigus vegetans (missing: Orphanet_79479, MONDO_0019322)
- IgA pemphigus (missing https://emedicine.medscape.com/article/1063776-overview)
- IgG/IgA pemphigus (missing)
- drug-induced pemphigus (missing https://emedicine.medscape.com/article/1063684-overview)
- radiotherapy-induced pemphigus (missing: requires new term)
- please merge cicatricial pemphigoid with mucous membrane pemphigoid (http://www.ebi.ac.uk/efo/EFO_1000680, DOID_11656, Orphanet_46486, MONDO_0018746). Preferred term is mucous membrane pemphigoid.
- ocular cicatricial pemphigoid (missing, NCIT_C84939, UMLS C1282359)
- Brunsting-Perry syndrome (missing, https://rarediseases.info.nih.gov/diseases/10454/brunsting-perry-syndrome); preferred term: localized cicatricial pemphigoid
- herpes gestationis (http://www.ebi.ac.uk/efo/EFO_1000709). Preferred term label is 'pemphigoid gestationis'.

### bullous skin disease

bullous skin disorder
vesiculobullous skin disease

### autoimmune bullous skin disease

Subepidermal autoimmune bullous disease
subepidermal autoimmune blistering disease
subepidermal autoimmune bullous diseases of the skin and mucosae
autoimmune diseases of the skin and mucous membrane

### pemphigus vulgaris

PV

### pemphigus foliaceus

PF

### mucous membrane pemphigoid

MMP
cicatricial pemphigoid
CP
Mucosynechial pemphigoid
Mucosal pemphigoid
vegetating cicatricial pemphigoid

### paraneoplastic pemphigus

PNP
paraneoplastic bullous pemphigoid
paraneoplastic pemphigoid

### pemphigus erythematosus

Senear-Usher syndrome
Seborrheic pemphigus
Seborrheic pemphigoid

### Anti-p200 pemphigoid

anti-laminin-γ1 pemphigoid

### IgA pemphigus

Immunoglobulin A (IgA) pemphigus
Immunoglobulin A pemphigus
immunoglobulin A (IgA)–mediated pemphigus
immunoglobulin A mediated pemphigus
subcorneal pustular dermatosis and monoclonal IgA

### IgG/IgA pemphigus

IgG/ IgA pemphigus

### mucous membrane pemphigoid

cicatricial pemphigoid

### ocular cicatricial pemphigoid

OCP

### localized cicatricial pemphigoid

Brunsting-Perry syndrome
Cicatricial Pemphigoid of the Brunsting-Perry Type
Localized Cicatricial Pemphigoid
localised cicatricial pemphigoid
Brunsting Perry Syndrome
Brunsting–Perry cicatricial pemphigoid

### drug-induced pemphigus

drug-induced pemphigoid
drug-related pemphigus
drug-triggered pemphigus
Biologic therapy-induced pemphigus
biologic-induced pemphigus
amoxicillin/clavulanic Acid-Induced Pemphigus Vulgaris
bucillamine-induced pemphigus vulgaris
drug-triggered pemphigus foliaceus
Pemphigus herpetiformis-type drug reaction

### radiotherapy-induced pemphigus

X-ray-induced pemphigus
radiotherapy-induced pemphigus
radiation-induced pemphigus
pemphigus induced by radiotherapy
radiotherapy-induced pemphigus vulgaris
radiation-induced pemphigus vulgaris
Paraneoplastic pemphigus triggered by radiotherapy
Pemphigus vulgaris induced by radiotherapy

###

Subepidermal autoimmune bullous diseases of the skin and mucosae comprise a large group of chronic diseases, including bullous pemphigoid, pemphigoid gestationis, mucous membrane pemphigoid, linear IgA bullous dermatosis, epidermolysis bullosa acquisita, and anti-p200 pemphigoid. These diseases are characterized by an antibody response toward structural components of the basement membrane zone, resulting in subepidermal blistering. [ PMID:29159697 ]

### pemphigus foliaceus

Pemphigus foliaceus is an autoimmune blistering disease of the skin with characteristic lesions that are scaly, crusted erosions, often on an erythematous base. [Wikipedia]

### paraneoplastic pemphigus

Pemphigus is a group of chronic autoimmune skin diseases characterised by blisters formation on the outer layer of the skin and the mucous membranes. Three clinical forms have been characterised, of which paraneoplastic pemphigus is extremely rare. [ Orphanet:63455 ]

### ocular cicatricial pemphigoid

A chronic autoimmune disorder that belongs to the mucous membrane pemphigoid disorders. It is characterized by bilateral scarring and opacification of the conjunctivae. It presents with pain and burning sensation in the eyes and photophobia. It leads to blindness. [ NCI ]

Ocular cicatricial pemphigoid (OCP) is a form of mucous membrane pemphigoid (a group of rare, chronic autoimmune disorders ) that affects the eyes. In the early stages, people with OCPgenerally experience chronic or relapsing conjunctivitis that is often characterized by tearing, irritation, burning, and/or mucus drainage. If left untreated, OCP can progress to severe conjunctiva scarring and vision loss. Involvement of other mucosal sites and the skin may also occur in OCP. The exact underlying cause is currently unknown. The treatment of OCP aims to slow disease progression and prevent complications. This usually involves long-term use of medications called immunomodulators which help regulate or normalize the immune system.[9044][9045] [ https://rarediseases.info.nih.gov/diseases/8759/ocular-cicatricial-pemphigoid ]

### pemphigus erythematosus

Pemphigus erythematosus (also known as "Senear–Usher syndrome") is simply a localized form of pemphigus foliaceus with features of lupus erythematosus. [ Wikipedia ]

### Anti-p200 pemphigoid

Anti-p200 pemphigoid is a rare subepidermal blistering skin disease. Clinically, anti-p200 pemphigoid is characterized by tense blisters and vesicles, erosions, and urticarial plaques, closely resembling bullous pemphigoid and the inflammatory variant of epidermolysis bullosa acquisita. [ PMID:24767733 ]

### IgA pemphigus

https://emedicine.medscape.com/article/1063776-overview

Immunoglobulin A (IgA) pemphigus is a group of newly characterized immune-mediated intraepidermal blistering skin diseases. Unlike typical immunoglobulin G (IgG)–mediated pemphigus, IgA pemphigus is characterized by tissue-bound and circulating IgA autoantibodies that target the desmosomal proteins of the epidermis [ https://emedicine.medscape.com/article/1063776-overview ] 

### IgG/IgA pemphigus

IgG/IgA pemphigus is defined by the presence of IgG and IgA cell surface deposits upon direct immunofluorescence (DIF) and/or circulating IgG and IgA autoantibodies upon indirect immunofluorescence. Previous reports of patients with IgG/IgA pemphigus are sparse [ PMID:26566588 ]

### pemphigus herpetiformis

https://emedicine.medscape.com/article/1064550-overview

Pemphigus herpetiformis is a rare autoimmune bullous skin disorder that is considered a clinical variant of pemphigus. Classically, it combines the clinical features of dermatitis herpetiformis with the immunopathologic features of pemphigus.

### pemphigus vegetans

Pemphigus vegetans (P Veg) is a rare clinical form of pemphigus.

### drug-induced pemphigus

https://emedicine.medscape.com/article/1063684-overview

Pemphigus is an autoimmune bullous disease characterized by blisters and erosions of the skin and mucous membranes. Several variants of the disease exist, including pemphigus vulgaris, pemphigus foliaceous, and drug-induced pemphigus. Patients with drug-induced pemphigus have autoantibodies that are either circulating or tissue bound.

## Suggested parent term

autoimmune bullous skin disease => autoimmune disease
autoimmune bullous skin disease => bullous skin disease
pemphigus => autoimmune bullous skin disease
pemphigus vulgaris => pemphigus
pemphigus foliaceus => pemphigus
paraneoplastic pemphigus => pemphigus
pemphigus erythematosus => pemphigus
IgA pemphigus => pemphigus
IgG/IgA pemphigus => pemphigus
pemphigus herpetiformis => pemphigus
drug-induced pemphigus => pemphigus
radiotherapy-induced pemphigus => pemphigus
mucous membrane pemphigoid => autoimmune bullous skin disease
ocular cicatricial pemphigoid => mucous membrane pemphigoid
localized cicatricial pemphigoid => mucous membrane pemphigoid
vegetating cicatricial pemphigoid=> mucous membrane pemphigoid
pemphigus vegetans => pemphigus vulgaris
Anti-p200 pemphigoid => autoimmune bullous skin disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment] 2018-02-15 09:54
@gkos-bio 
Thanks. We will aim to address this request, and your other recent ones, in time for the March EFO release (March 15th).

**Comment by siiraa** [comment] 2018-02-26 17:20
@gkos-bio 
Please provide a webulous template to request new terms, add synonyms/xRefs. You should be able to do this in Webulous the same way we have always done it.

Thank you,

**Comment by siiraa** [comment] 2018-02-27 14:14
Completed:
- Renamed cicatricial pemphigoid to mucous membrane pemphigoid as rdfs:label, added other synonyms
- Added missing xRefs to pemphigus

What do you want us to do with pemphigoid vulgaris?

**Comment by siiraa** [comment] 2018-02-27 14:14
Request:
- Please provide the missing term request in a spreadsheet format. Thank you.

**Comment by siiraa** [comment] 2018-02-28 09:45
info transformed to spreadsheet started at https://docs.google.com/spreadsheets/d/1jzFsh7lmi4-V4Gd5aaDcy-j6ghTTBKuyJxw9bPvYecM/edit#gid=19432365

**Comment by siiraa** [comment] 2018-02-28 10:24
Hi @gkos-bio ,
### Please review https://docs.google.com/spreadsheets/d/1jzFsh7lmi4-V4Gd5aaDcy-j6ghTTBKuyJxw9bPvYecM/edit#gid=19432365

I think some errors may have occurred when you copied/pasted from your spreadsheet, i have tried to put the definitions of your terms in the right place but this needs your review. Four terms are still missing definitions.  Once we have these definitions, we can process the new terms. We apologise for the confusion of the term request instruction on the github ticket form. It would have been easier if we have access to your spreadsheet (which looked like you had it in spreadsheet before transforming into this ticket). I have edited the instruction suggesting the attachement of the spreadsheet. @simonjupp will review and update it to master branch soon. Thank you.

_Please remember to supply the four definitions_

**Comment by siiraa** [comment] 2018-02-28 10:26
Terms needed definitions:
- paraneoplastic pemphigus
- radiotherapy-induced pemphigus
- localised cicatricial pemphigoid
- vegetating cicatricial pemphigoid

**Comment by siiraa** [comment] 2018-02-28 10:28
Developer's note: (@paolaroncaglia / @simonjupp )
[-]Once the spreadsheet is completed, run webulous disease and this can be closed.

**Comment by paolaroncaglia** [comment] 2018-03-14 16:18
Update: Zoe and I added the 4 missing definitions in the Webulous spreadsheet, they look acceptable to us. We will probably not manage to push this to release just yet though. @gkos-bio if you have a chance, please review this Webulous spreadsheet - note it's not the same link as above: https://docs.google.com/spreadsheets/d/1vnwfQurBQBq14I_OOV34XmS9If5e_N4qrnnTpm8WIPY/edit?ts=5aa92078#gid=19432365 (second tab). Thanks.

**Comment by paolaroncaglia** [comment] 2018-04-05 13:44
FYI - We committed the Webulous file and related changes (EFO URIs), but committed without using the hashtag. The commit message appears in GitHub but not in the ticket itself.
Will add new terms IDs below.

**Comment by paolaroncaglia** [comment] 2018-04-05 13:50
Here are the IDs of the new terms:

anti-p200 pemphigoid
EFO_0008597

autoimmune bullous skin disease
EFO_0008598

pemphigus foliaceus
EFO_0008601

paraneoplastic pemphigus
EFO_0008602

pemphigus erythematosus
EFO_0008603

IgA pemphigus
EFO_0008604

IgG/IgA pemphigus
EFO_0008605

pemphigus herpetiformis
EFO_0008606

drug-induced pemphigus
EFO_0008607

radiotherapy-induced pemphigus
EFO_0008608

ocular cicatricial pemphigoid
EFO_0008610

localised cicatricial pemphigoid
EFO_0008611

vegetating cicatricial pemphigoid
EFO_0008612

pemphigus vegetans
EFO_0008613

**Comment by paolaroncaglia** [comment] 2018-12-18 09:54
Re-opening this issue because it looks like 'vesiculobullous skin disease' still needs to be merged with 'bullous skin disease'. Look at representation in EFO 3 and MONDO, too.

**Comment by paolaroncaglia** [comment] 2019-03-12 13:18
Note for self: might be useful to note a useful source for definitions and synonyms for epidermolysis bullosa (currently child of 'vesiculobullous skin disease' in EFO) that Peter Robinson pointed out to MONDO: https://www.ncbi.nlm.nih.gov/pubmed/24690439.
(FYI, the MONDO ticket is https://github.com/monarch-initiative/mondo/issues/630.)

**Comment by paolaroncaglia** [comment] 2019-05-13 13:09
@gkos-bio 
In your original request (first bullet point in https://github.com/EBISPOT/efo/issues/75#issue-296335868), you suggested to merge 'vesiculobullous skin disease' (http://www.ebi.ac.uk/efo/EFO_1000774) with 'bullous skin disease', and to have 'vesiculobullous skin disease' as a synonym of 'bullous skin disease'. However, based on the etimology of the terms (see https://en.wikipedia.org/wiki/Vesiculobullous_disease), on search results and on usage in other ontologies (see http://purl.obolibrary.org/obo/MONDO_0006617), I propose to:
- [ ] Keep 'vesiculobullous skin disease' as the parent term
- [ ] Expand its definition based on https://en.wikipedia.org/wiki/Vesiculobullous_disease
- [ ] Obsolete 'bullous skin disease' and replace it with 'autoimmune bullous skin disease' (the former is textually defined as the latter, and has the latter as its only child, a bad smell confirmed by usage in other medical ontologies)
Please let me know if you have any objection. Thanks!

**Comment by paolaroncaglia** [comment] 2019-05-28 11:46
@gkos-bio 
FYI, this is all done now.

**Closed** 2019-05-30 10:03 UTC
Labels: OpenTargets
